### ISSUE TITLE
Tracking phoenix 1.3 issues

### ISSUE THREAD

**Issue by fire** [sublimecoder/ex_admin#1]
This issue tracks phoenix 1.3.

**Comment by fire** [comment]
Verify that both work.

* mix install task is not working 
* updates are not working on the admin interface

**Comment by sublimecoder** [comment]
@fire updates appear to be working. I am looking into testing the mix admin install task. I will get this fixed in the next week or so.

**Comment by sublimecoder** [comment]
@fire admin.install is working now on master.
