### ISSUE TITLE
Update structure to phoenix 1.3

### ISSUE THREAD

**Issue by sublimecoder** [sublimecoder/ex_admin#12]
update the structure of ex_admin to be more in line with the structure of a phoenix 1.3 application.

**Comment by scottswezey** [comment]
Given the scope of changes potentially needed for 1.3 support, I've held off on any other changes. If there is anything I can do to help with the 1.3 project, please let me know. Otherwise, I'll monitor this issue and jump in once the code base is less in flux and the 1.3 changes are mostly done.

**Comment by vraravam** [comment]
bump!
As this codebase has been upgraded to phx 1.4, can this issue be resolved?

**Comment by sublimecoder** [comment]
Yes it can. There is still some clean up that needs to happen, but those things can be opened in separate issues.

--
Jared Smith
