### ISSUE TITLE
Readme references old project and wiki

### ISSUE THREAD

**Issue by scottswezey** [sublimecoder/ex_admin#13]
I've noticed that several links in the readme and other docs contain links to the original smallpen99 project and github wiki. I'm planning to go through all of the docs and update them to reference sublimecoder's version of this project. I'll also work on cloning the wiki over to this project.

**Comment by sublimecoder** [comment]
Awesome 👍 appreciate it!

**Comment by scottswezey** [comment]
All work to close this issue should now be done.

- [x] Updated readme and other doc files. See PR #14 
- [ ] Merge all or part of PR #14 
- [x] Cloned Wiki from smallpen99's project
