### ISSUE TITLE
Testing environment

### ISSUE THREAD

**Issue by scottswezey** [sublimecoder/ex_admin#18]
@sublimecoder Do you have a project (that can be shared) for testing updated versions of ex_admin? The contributing docs suggest two projects from the original author, but both are very out of date and need dependencies that conflict with this version of ex_admin / mix.exs.

Thanks

**Comment by sublimecoder** [comment]
I don’t have a base app i use for that yet, I’ve been using projects I use ex_admin on and so far that’s working ok. I’m planning on making one that will serve as a demo, but so far have had other obligations get in the way.

If you’d like to make one I’d be happy to review it and we can get it added to the docs.

--
Jared Smith
