### ISSUE TITLE
Fix Admin Install mix task

### ISSUE THREAD

**Issue by sublimecoder** [sublimecoder/ex_admin#7]
The admin install mix task does not utilize the phoenix 1.3 structure and should be converted so that it just works with new applications moving forward.

**Comment by jc00ke** [comment]
Is there a short-term way around this?

**Comment by sublimecoder** [comment]
You should be able to run the script and copy the files into the desired locations. Is the command failing entirely for you? I can see if I can fix it this week. Pretty sure it’s just some copy and replace to fix it.

--
Jared Smith

**Comment by jc00ke** [comment]
It was balking at locating `brunch-config.js` and then a few things after that. Lemme whip up a PR real quick.

**Comment by sublimecoder** [comment]
Should be fixed now.
